apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: spark-template
  namespace: cx-encore-di-entra-ns
  labels:
    workflows.argoproj.io/controller-instanceid: argo-workflows-dev
spec:
  entrypoint: spark-dag

  arguments:
    parameters:
      - name: run-id
        value: "{{workflow.uid}}"
      - name: dag-id
        value: "{{workflow.name}}"
      - name: load-image
        value: "encoreacrdev.azurecr.io/database-to-tmp-storage:TEST-<tag>"
      - name: polaris-image
        value: "encoreacrdev.azurecr.io/encore-di-tmp-storage-to-iceberg:bc8be16-202604131139"

  templates:
    - name: spark-dag
      dag:
        tasks:
          - name: data-load
            template: spark-data-load

          - name: write-to-polaris
            dependencies: [data-load]
            template: spark-write-to-polaris

    - name: spark-data-load
      resource:
        action: create
        successCondition: status.applicationState.state == COMPLETED
        failureCondition: status.applicationState.state == FAILED
        manifest: |
          apiVersion: sparkoperator.k8s.io/v1beta2
          kind: SparkApplication
          metadata:
            generateName: data-load-
            namespace: cx-encore-di-entra-ns
          spec:
            type: Python
            pythonVersion: "3"
            mode: cluster
            image: "{{workflow.parameters.load-image}}"
            imagePullPolicy: Always
            mainApplicationFile: local:///opt/app/src/main.py
            sparkVersion: 4.0.1
            timeToLiveSeconds: 3000
            restartPolicy:
              type: Never

            nodeSelector: {}

            sparkConf:
              spark.kubernetes.submission.waitAppCompletion: "true"
              spark.kubernetes.driver.deleteOnTermination: "false"
              spark.kubernetes.executor.deleteOnTermination: "false"
              spark.kubernetes.driver.pod.seccompProfile.type: RuntimeDefault
              spark.kubernetes.executor.pod.seccompProfile.type: RuntimeDefault
              spark.sql.parquet.datetimeRebaseModeInWrite: LEGACY
              spark.sql.parquet.int96RebaseModeInWrite: LEGACY
              spark.sql.session.timeZone: UTC
              spark.pyspark.python: python3
              spark.pyspark.driver.python: python3
              spark.eventLog.enabled: "false"
              spark.ui.showConsoleProgress: "false"
              spark.log.level: "WARN"

            driver:
              serviceAccount:  encore-di-entra      
              coreRequest: "100m"
              coreLimit: "1"
              memory: "1024m"
              env:
                - name: DAG_ID
                  value: "{{workflow.parameters.dag-id}}"
                - name: RUN_ID
                  value: "{{workflow.parameters.run-id}}"
              envFrom:
                - configMapRef:
                    name: encore-landing-storage-config
                - secretRef:
                    name: azure-credentials
                - configMapRef:
                    name: uc-ewms-db-mssql-config
                - secretRef:
                    name: uc-ewms-db-mssql-secret
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                capabilities:
                  drop: ["ALL"]
              labels:
                version: "4.0.1"

            executor:
              instances: 1
              coreRequest: "100m"
              coreLimit: "1"
              memory: "2048m"
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                capabilities:
                  drop: ["ALL"]
              labels:
                version: "3.5.1"
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"

    - name: spark-write-to-polaris
      resource:
        action: create
        successCondition: status.applicationState.state == COMPLETED
        failureCondition: status.applicationState.state == FAILED
        manifest: |
          apiVersion: sparkoperator.k8s.io/v1beta2
          kind: SparkApplication
          metadata:
            generateName: write-to-polaris-
            namespace: cx-encore-di-entra-ns
          spec:
            type: Python
            pythonVersion: "3"
            mode: cluster
            image: "{{workflow.parameters.polaris-image}}"
            imagePullPolicy: Always
            mainApplicationFile: local:///opt/app/src/main.py
            sparkVersion: 4.0.1
            timeToLiveSeconds: 3000
            restartPolicy:
              type: Never

            nodeSelector: {}

            sparkConf:
              spark.kubernetes.submission.waitAppCompletion: "true"
              spark.kubernetes.driver.deleteOnTermination: "false"
              spark.kubernetes.executor.deleteOnTermination: "false"
              spark.kubernetes.driver.pod.seccompProfile.type: RuntimeDefault
              spark.kubernetes.executor.pod.seccompProfile.type: RuntimeDefault
              spark.sql.parquet.datetimeRebaseModeInWrite: LEGACY
              spark.sql.parquet.int96RebaseModeInWrite: LEGACY
              spark.sql.session.timeZone: UTC
              spark.pyspark.python: python3
              spark.pyspark.driver.python: python3
              spark.eventLog.enabled: "false"
              spark.ui.showConsoleProgress: "false"
              spark.log.level: "WARN"

            driver:
              serviceAccount:  encore-di-entra      
              coreRequest: "100m"
              coreLimit: "1"
              memory: "1024m"
              env:
                - name: DAG_ID
                  value: "{{workflow.parameters.dag-id}}"
                - name: RUN_ID
                  value: "{{workflow.parameters.run-id}}"
              envFrom:
                - configMapRef:
                    name: encore-landing-storage-config
                - secretRef:
                    name: azure-credentials

              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                capabilities:
                  drop: ["ALL"]
              labels:
                version: "4.0.1"

            executor:
              instances: 1
              coreRequest: "100m"
              coreLimit: "1"
              memory: "2048m"
              securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 1000
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: false
                capabilities:
                  drop: ["ALL"]
              labels:
                version: "3.5.1"
              env:
                - name: PYTHONUNBUFFERED
                  value: "1"
