apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: spark-encore-argo-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: spark-encore-argo-manager
subjects:
  - kind: ServiceAccount
    name: encore-argo
