apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflow
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-server
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-workflows-workflow-controller
